export const playerConstants = {
  CREATE_REQUEST: 'PLAYERS_CREATE_REQUEST',
  CREATE_SUCCESS: 'PLAYERS_CREATE_SUCCESS',
  CREATE_FAILURE: 'PLAYERS_CREATE_FAILURE',

  GETALL_REQUEST: 'PLAYERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'PLAYERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'PLAYERS_GETALL_FAILURE',

  DELETE_REQUEST: 'PLAYERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'PLAYERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'PLAYERS_DELETE_FAILURE'
};
