export const userConstants = {
  CREATE_REQUEST: 'USER_CREATE_REQUEST',
  CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
  CREATE_FAILURE: 'USER_CREATE_FAILURE',

  GET_REQUEST: 'USER_GET_REQUEST',
  GET_SUCCESS: 'USER_GET_SUCCESS',
  GET_FAILURE: 'USER_GET_FAILURE'
};
